CREATE TABLE message (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message TEXT NOT NULL,
    sender VARCHAR(255) NOT NULL,
    product UUID NOT NULL,
    date_sent TIMESTAMP NOT NULL,
    date_received TIMESTAMP,
    status VARCHAR(32) NOT NULL
);

CREATE INDEX idx_message_sender ON message (sender);
CREATE INDEX idx_message_product ON message (product);
